name: Deploy stack

on:
  workflow_dispatch:
    inputs:
      master_ip:
        description: Master ip
        type: string
        default: ""
        required: true
      ssh_user:
        description: SSH user
        type: string
        required: true
        default: ""
      environment:
        description: Environment
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - demo
      action:
        description: Action
        required: true
        type: choice
        default: "create"
        options:
          - create
          - delete

jobs:
  create_stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Setup pulumi
        uses: pulumi/actions@v6

      - name: Setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat > ~/.ssh/config << 'EOF'
          Host *
          StrictHostKeyChecking no
          EOF

      - name: Create kube config
        run: |
          SSH_USER=${{ github.event.inputs.ssh_user }}
          MASTER_IP=${{ github.event.inputs.master_ip }}
          mkdir -p ~/.kube
          ssh $SSH_USER@$MASTER_IP cat "/etc/rancher/k3s/k3s.yaml" > ~/.kube/config
          chmod 600 ~/.kube/config
          sed -i "s/127.0.0.1/$MASTER_IP/g" ~/.kube/config

      - name: Install dependencies
        working-directory: ./infra
        run: npm install

      - name: Pulumi login
        working-directory: ./infra
        run: pulumi login --local

      - name: Choose stack
        working-directory: ./infra
        run: |
          pulumi stack select ${{ github.event.inputs.environment }} --create

      - name: Deploy stack
        working-directory: ./infra
        run: pulumi up --yes
