name: Deploy stack

on:
  workflow_dispatch:
    inputs:
      ssh_user:
        description: Choose a ssh user
        type: string
        required: true
        default: ""
      master_ip:
        description: Master ip
        type: string
        default: ""
        required: true
      environment:
        description: Environment
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - demo
      action:
        description: Action
        required: true
        type: choice
        default: "deploy"
        options:
          - deploy
          - delete

jobs:
  deploy_stack:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      id-token: write
    env:
      PULUMI_CONFIG_PASSPHRASE: ""
      K8S_AUDIENCE: ${{ secrets.K8S_AUDIENCE }}
      SSH_USER: ${{ github.event.inputs.ssh_user }}
      MASTER_IP: ${{ github.event.inputs.master_ip }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Setup pulumi
        uses: pulumi/actions@v6

      - uses: ./.github/actions/setup-ssh
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Download latest pulumi state
      #   run: |
      #     npm install @octokit/rest
      #     node ./scripts/download-artifact.js
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #     GITHUB_REPOSITORY: ${{ github.repository }}
      #     ENVIRONMENT: ${{ github.event.inputs.environment }}
      #   continue-on-error: true

      - name: Setup k3s auth
        uses: ./.github/actions/setup-k3s-auth
        with:
          master_ip: "$MASTER_IP"
          k3s_cert: ${{ secrets.K3S_CERT }}

      - name: Copy pulumi state
        run: |
          mkdir -p /home/runner/.pulumi/stacks
          echo "Copying pulumi state..."
          scp -r $SSH_USER@$MASTER_IP:/var/pulumi/state/.pulumi/stacks/* ./pulumi/stacks/ || echo "No pulumi state found"

      - name: Check pulumi folder
        run: |
          echo "----------------"
          if [[ -d ~/.pulumi/stacks ]]; then
            ls ~/.pulumi/stacks
          else
            echo "no pulumi folder"
          fi
          echo "----------------"

      - name: Install dependencies
        working-directory: ./infra
        run: npm install

      - name: Pulumi login
        run: pulumi login --local

      - name: Choose stack
        working-directory: ./infra
        run: |
          pulumi stack select ${{ github.event.inputs.environment }} || \
          pulumi stack select ${{ github.event.inputs.environment }} --create

      - name: Deploy stack
        working-directory: ./infra
        if: ${{ github.event.inputs.action == 'deploy' }}
        run: pulumi up --yes

      # - name: Save pulumi state
      #   if: ${{ github.event.inputs.action == 'deploy' }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: pulumi-state-${{ github.event.inputs.environment }}
      #     path: ~/.pulumi/stacks
      #     retention-days: 400

      - name: Remove stack
        working-directory: ./infra
        if: ${{ github.event.inputs.action == 'delete' }}
        run: |
          pulumi destroy --yes
          pulumi stack rm ${{ github.event.inputs.environment }} --yes --force

      - name: Save pulumi state
        run: |
          echo "Saving pulumi state..."
          scp -r ~/.pulumi/stacks/* $SSH_USER@$MASTER_IP:/var/pulumi/state/.pulumi/stacks/
          echo "Pulumi state saved"
      # - name: Delete pulumi state
      #   if: ${{ github.event.inputs.action == 'delete' }}
      #   uses: actions/github-script@v7
      #   continue-on-error: true
      #   with:
      #     script: |
      #       const artifacts = await github.rest.actions.listArtifactsForRepo({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #       });

      #       for (const artifact of artifacts.data.artifacts) {
      #         if (artifact.name === 'pulumi-state-${{ github.event.inputs.environment }}') {
      #           await github.rest.actions.deleteArtifact({
      #             owner: context.repo.owner,
      #             repo: context.repo.repo,
      #             artifact_id: artifact.id,
      #           });
      #         }
      #       }
