name: Deploy stack

on:
  workflow_dispatch:
    inputs:
      ssh_user:
        description: SSH user
        type: string
        required: true
        default: ""
      master_ip:
        description: Master ip
        type: string
        default: ""
        required: true
      stack:
        type: choice
        required: true
        description: Select a stack
        options:
          - core
          - dev
          - demo
      action:
        description: Action
        required: true
        type: choice
        default: "deploy"
        options:
          - deploy
          - delete

jobs:
  deploy_stack:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      id-token: write
    env:
      PULUMI_CONFIG_PASSPHRASE: ""
      K8S_AUDIENCE: ${{ secrets.K8S_AUDIENCE }}
      SSH_USER: ${{ github.event.inputs.ssh_user }}
      MASTER_IP: ${{ github.event.inputs.master_ip }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Setup pulumi
        uses: pulumi/actions@v6

      - name: Setup SSH
        uses: ./.github/actions/setup-ssh
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup k3s auth
        uses: ./.github/actions/setup-k3s-auth
        with:
          master_ip: "$MASTER_IP"
          k3s_cert: ${{ secrets.K3S_CERT }}

      - name: Copy pulumi state
        run: |
          mkdir -p /home/runner/.pulumi/stacks
          echo "Copying pulumi state..."
          scp -r $SSH_USER@$MASTER_IP:/var/pulumi/state/.pulumi/stacks/* ~/.pulumi/stacks/ 2>/dev/null && echo "Pulumi state copied" || echo "No pulumi state found"

      - name: Install dependencies
        working-directory: ./infra
        run: npm install

      - name: Pulumi login
        run: pulumi login --local

      - name: Deploy Core Stack
        if: github.event.inputs.stack == 'core' && github.event.inputs.action == 'deploy'
        working-directory: ./infra/core
        run: |
          pulumi stack select core || \
          pulumi stack select core --create
          pulumi up --yes --skip-preview
          echo ""
          echo "Waiting for cert-manager to be available..."
          kubectl wait --for=condition=Available deployment/cert-manager -n cert-manager --timeout=5m
          kubectl wait --for=condition=Available deployment/cert-manager-webhook -n cert-manager --timeout=5m
          kubectl wait --for=condition=Available deployment/cert-manager-cainjector -n cert-manager --timeout=5m

          echo ""
          echo "Give 40s for the webhook..."
          sleep 40

          echo ""
          echo "Waiting for certificate to be ready..."
          kubectl wait --for=condition=Ready certificate/tls-cert -n cert-manager --timeout=6m || {
              echo "❌ Certificate failed"
              kubectl describe certificate tls-cert -n cert-manager
              kubectl get certificaterequest -n cert-manager
              kubectl get challenges -n cert-manager
              kubectl describe challenge -n cert-manager 2>/dev/null || true
              exit 1
          }
          echo "✅ Certificate ready!"

      - name: Deploy Environment Stack
        working-directory: ./infra/stacks/${{ github.event.inputs.stack }}
        if: github.event.inputs.action == 'deploy' && github.event.inputs.stack != 'core'
        run: |
          pulumi stack select ${{ github.event.inputs.stack }} || \
          pulumi stack select ${{ github.event.inputs.stack }} --create
          pulumi up --yes --skip-preview

      - name: Remove Core Stack
        working-directory: ./infra/core
        if: github.event.inputs.stack == 'core' && github.event.inputs.action == 'delete'
        run: |
          pulumi stack select core
          pulumi destroy --yes

      - name: Remove Environment Stack
        working-directory: ./infra/stacks/${{ github.event.inputs.stack }}
        if: github.event.inputs.stack != 'core' && github.event.inputs.action == 'delete'
        run: |
          pulumi stack select ${{ github.event.inputs.stack }}
          pulumi destroy --yes

      - name: Save pulumi state
        run: |
          echo "Saving pulumi state..."
          scp -r ~/.pulumi/stacks/* $SSH_USER@$MASTER_IP:/var/pulumi/state/.pulumi/stacks/
          echo "Pulumi state saved"
