name: K3s cluster setup

on:
  workflow_dispatch:
    inputs:
      action:
        description: Choose an action
        type: choice
        default: create
        required: true
        options: [install, destroy]
      master_ip:
        description: Choose a master ip
        type: string
        required: true
        default: ""
      agents_ips:
        description: Choose agent ips (comma separated ip1,ip2...)
        type: string
        required: true
        default: ""
      ssh_user:
        description: Choose a ssh user
        type: string
        required: true
        default: ""
jobs:
  k3s-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-ssh
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup cluster
        if: github.event.inputs.action == 'install'
        run: |
          chmod +x ./scripts/create-cluster.sh
          echo "Executing create shell script..."
          ./scripts/create-cluster.sh \
            ${{ github.event.inputs.master_ip }} \
            ${{ github.event.inputs.agents_ips }} \
            ${{ github.event.inputs.ssh_user }}

      - name: Setup GitHub OIDC RBAC
        if: github.event.inputs.action == 'install'
        run: |
          chmod +x ./scripts/setup-github-oidc-rbac.sh
          ./scripts/setup-github-oidc-rbac.sh \
            "${{ github.event.inputs.master_ip }}" \
            "${{ github.event.inputs.ssh_user }}" \
            "${{ github.repository_owner }}" \
            "${{ github.event.repository.name }}"

      - name: Destroy cluster
        if: github.event.inputs.action == 'destroy'
        run: |
          chmod +x ./scripts/delete-cluster.sh
          echo "Executing delete shell script..."
          ./scripts/delete-cluster.sh \
            ${{ github.event.inputs.master_ip }} \
            ${{ github.event.inputs.agents_ips }} \
            ${{ github.event.inputs.ssh_user }}

      - name: Clean ssh
        if: always()
        run: |
          rm -rf .ssh
